<?php

// return a temp directory location found under the site's /sites/default directory
function _user0_webauth_tmp_directory() {
  $base_path = substr($_SERVER['SCRIPT_FILENAME'],0,strpos($_SERVER['SCRIPT_FILENAME'],'index.php'));
  return $base_path . conf_path() . '/user0_webauth/tmp';
}

// implement hook_stanford_r25_link, returning a link to the external authentication script
function user0_webauth_stanford_r25_external_link($link_text = 'Authenticate') {

  global $base_url, $base_path, $cookie_domain;
  $secure_base_url = str_replace('http:', 'https:', $base_url) . '/';
  $user0_webauth_url = $secure_base_url . conf_path() . 
    '/user0_webauth/user0_webauth.php';
  $destination = drupal_get_destination();
  $options = array('attributes'=>array('class'=>array('button','btn-giving')),
    'query'=>array(
      'base_path' => $base_path,
      'cookie_domain' => $cookie_domain,
      'destination' => $destination['destination']));
  return l($link_text, $user0_webauth_url, $options);
}

// implement hook stanford_r25_external_user returning an array of information about the user
function user0_webauth_stanford_r25_external_user() {
  $return_data = false;
  if (!empty($_COOKIE['user0_webauth'])) {
    $filename = _user0_webauth_tmp_directory() . '/' . $_COOKIE['user0_webauth'];
    $user0_info = array();
    if (file_exists($filename) && time()-filemtime($filename) < 36000) {
      $user0_info = json_decode(file_get_contents($filename),true);
    }
    if (empty($user0_info) || empty($user0_info['R25_EXTERNAL_UID'])) {
      watchdog('stanford_r25','External login failed. Missing data file or uid.');
      @unlink($filename);
    } else {
      $return_data = $user0_info;
    }
  }
  return $return_data;
}

// implement hook stanford_r25_external_user_display to return a contact information string about the user
function user0_webauth_stanford_r25_external_user_display($user_info) {
    $contact = '';
    if (!empty($user_info['R25_EXTERNAL_DISPLAYNAME'])) $contact .= $user_info['R25_EXTERNAL_DISPLAYNAME']."\r\n";
    if (!empty($user_info['R25_EXTERNAL_OU'])) $contact .= $user_info['R25_EXTERNAL_OU'] . "\r\n";
    if (!empty($user_info['R25_EXTERNAL_MAIL'])) $contact .= 'Mail: '.$user_info['R25_EXTERNAL_MAIL'] . "\r\n";
    if (!empty($user_info['R25_EXTERNAL_TELEPHONENUMBER'])) $contact .= 'Phone: '.$user_info['R25_EXTERNAL_TELEPHONENUMBER']."\r\n";
    if (!empty($user_info['R25_EXTERNAL_POSTALADDRESS'])) $contact .= 'Address: '.$user_info['R25_EXTERNAL_POSTALADDRESS'] . "\r\n";
    return $contact;
}

// a cron function to clean up files in the temp directory more than 10 hours old
function user0_webauth_cron() {
        
    // cleanup old tmp files
    $seconds_old = 36000;
    $directory = _user0_webauth_tmp_directory();
            
    if( !$dirhandle = @opendir($directory) )
        return;

    while( false !== ($filename = readdir($dirhandle)) ) {
        if( $filename != "." && $filename != ".." ) {
            $filename = $directory. "/". $filename;
            if( @filemtime($filename) < (time()-$seconds_old) ) {
                @unlink($filename);
            }
        }
    }
}

